### ISSUE TITLE
Add missing images to docs of benjamin options

### ISSUE THREAD

**Issue by joostdecock** [freesewing/markdown#39]
@AlfaLyr says they used to be there, but now they are not...

**Comment by joostdecock** [comment]
The images are here: https://github.com/joostdecock/site/tree/develop/nuxt/static/img/patterns/benjamin/options

They need to be added, but we also have to update the markdown to include/show them.

**Comment by woutervdub** [comment]
Of course, adding them is easy. My concern is that in the old Freesewing, you did not need to add the image to the option markdown. The site would include the image automagically. The question now becomes; Will v2 of Freesewing do the same, or are we altering this behaviour?

**Comment by joostdecock** [comment]
These have been added. For missing illustrations in general, please follow https://github.com/freesewing/freesewing.org/issues/190
