### ISSUE TITLE
typing error on the page "FreeSewing Revenue Pledge"

### ISSUE THREAD

**Issue by Slylele** [freesewing/markdown#66]
In the page "FreeSewing Revenue Pledge" a "C" is missing in the question at the end of the paragraph "Noblesse oblige": it's written "ould I use the money" instead of "Could I use the money".
https://en.freesewing.org/docs/about/pledge/

**Comment by joostdecock** [comment]
Thanks for reporting this. I've updated it, but I still need to deploy the fix on the website.
